Creating a scatter plot that shows how the tumor volume changes over time for each treatment.
Creating a scatter plot that shows how the number of metastatic (cancer spreading) sites changes over time for each treatment.
Creating a scatter plot that shows the number of mice still alive through the course of treatment (Survival Rate)
Creating a bar graph that compares the total % tumor volume change for each drug across the full 45 days.

In [24]:
#Import dependencies
import pandas as pd
import matplotlib as plt
import numpy as np
import os

In [25]:
#Read in csv files
filepath = os.path.join("raw_data","clinicaltrial_data.csv")
filepath2 = os.path.join("raw_data","mouse_drug_data.csv")

In [26]:
clinical_rawdata_df = pd.read_csv(filepath, low_memory = False)
clinical_rawdata_df.head()

  Mouse ID  Timepoint  Tumor Volume (mm3)  Metastatic Sites
0     b128          0                45.0                 0
1     f932          0                45.0                 0
2     g107          0                45.0                 0
3     a457          0                45.0                 0
4     c819          0                45.0                 0

In [27]:
mouse_rawdata_df = pd.read_csv(filepath2, low_memory = False)
mouse_rawdata_df.head()

#1 duplicate = g989 mouse_rawdata_df.nunique() vs count()

  Mouse ID      Drug
0     f234  Stelasyn
1     x402  Stelasyn
2     a492  Stelasyn
3     w540  Stelasyn
4     v764  Stelasyn

In [28]:
#Merge both tables
merged_rawdata = pd.merge(clinical_rawdata_df,mouse_rawdata_df, on="Mouse ID")
merged_rawdata=pd.DataFrame(merged_rawdata)
merged_rawdata.head()

  Mouse ID  Timepoint  Tumor Volume (mm3)  Metastatic Sites       Drug
0     b128          0           45.000000                 0  Capomulin
1     b128          5           45.651331                 0  Capomulin
2     b128         10           43.270852                 0  Capomulin
3     b128         15           43.784893                 0  Capomulin
4     b128         20           42.731552                 0  Capomulin

In [29]:
#Creating a scatter plot that shows how the tumor volume changes over time for each treatment. X=timepoint y=volume
#Group by treatment, by mouse ID

grouped_tumorvol = merged_rawdata.groupby(["Drug","Timepoint"]).agg({"Tumor Volume (mm3)":"mean"})
grouped_tumorvol= pd.DataFrame(grouped_tumorvol)
grouped_tumorvol

                     Tumor Volume (mm3)
Drug      Timepoint
Capomulin 0                   45.000000
          5                   44.266086
          10                  43.084291
          15                  42.064317
          20                  40.716325
          25                  39.939528
          30                  38.769339
          35                  37.816839
          40                  36.958001
          45                  36.236114
Ceftamin  0                   45.000000
          5                   46.503051
          10                  48.285125
          15                  50.094055
          20                  52.157049
          25                  54.287674
          30                  56.769517
          35                  58.827548
          40                  61.467895
          45                  64.132421
Infubinol 0                   45.000000
          5                   47.062001
          10                  49.403909
          15                  51.296397
          20                  53.197691
          25                  55.715252
          30                  58.299397
          35                  60.742461
          40                  63.162824
          45                  65.755562
...                                 ...
Ramicane  0                   45.000000
          5                   43.944859
          10                  42.531957
          15                  41.495061
          20                  40.238325
          25                  38.974300
          30                  38.703137
          35                  37.451996
          40                  36.574081
          45                  34.955595
Stelasyn  0                   45.000000
          5                   47.527452
          10                  49.463844
          15                  51.529409
          20                  54.067395
          25                  56.166123
          30                  59.826738
          35                  62.440699
          40                  65.356386
          45                  68.438310
Zoniferol 0                   45.000000
          5                   46.851818
          10                  48.689881
          15                  50.779059
          20                  53.170334
          25                  55.432935
          30                  57.713531
          35                  60.089372
          40                  62.916692
          45                  65.960888

[100 rows x 1 columns]

In [30]:
# Scatter plot
#list =grouped_tumorvol["Drug"]
#color = orchid, firebrik, dark salmon, cyan, plum, navy, lightskyblue, green, gold, red
plt.scatter(grouped_tumorvol["Timepoint"], grouped_tumorvol["Tumor Volume (mm3)"])
#plt.scatter(grouped["No. of rides"], grouped["Avg Fare"], s=grouped["driver_count"], c = grouped["color ref"])

AttributeError: module 'matplotlib' has no attribute 'scatter'

In [31]:
#Creating a scatter plot that shows how the number of metastatic (cancer spreading) sites 
#changes over time for each treatment. 
metastatic_change = merged_rawdata.groupby(["Drug","Timepoint"]).mean()["Metastatic Sites"]
metastatic_change=pd.DataFrame(metastatic_change)
metastatic_change

                     Metastatic Sites
Drug      Timepoint
Capomulin 0                  0.000000
          5                  0.160000
          10                 0.320000
          15                 0.375000
          20                 0.652174
          25                 0.818182
          30                 1.090909
          35                 1.181818
          40                 1.380952
          45                 1.476190
Ceftamin  0                  0.000000
          5                  0.380952
          10                 0.600000
          15                 0.789474
          20                 1.111111
          25                 1.500000
          30                 1.937500
          35                 2.071429
          40                 2.357143
          45                 2.692308
Infubinol 0                  0.000000
          5                  0.280000
          10                 0.666667
          15                 0.904762
          20                 1.050000
          25                 1.277778
          30                 1.588235
          35                 1.666667
          40                 2.100000
          45                 2.111111
...                               ...
Ramicane  0                  0.000000
          5                  0.120000
          10                 0.250000
          15                 0.333333
          20                 0.347826
          25                 0.652174
          30                 0.782609
          35                 0.952381
          40                 1.100000
          45                 1.250000
Stelasyn  0                  0.000000
          5                  0.240000
          10                 0.478261
          15                 0.782609
          20                 0.952381
          25                 1.157895
          30                 1.388889
          35                 1.562500
          40                 1.583333
          45                 1.727273
Zoniferol 0                  0.000000
          5                  0.166667
          10                 0.500000
          15                 0.809524
          20                 1.294118
          25                 1.687500
          30                 1.933333
          35                 2.285714
          40                 2.785714
          45                 3.071429

[100 rows x 1 columns]

In [34]:
x_axis = np.arange[0, range(0,50), 5]
x_axis
#plt.scatter(metastatic_change["Timepoint"], metastatic_change["Metastatic Sites"], marker ="o", linestyle = "--")

TypeError: 'builtin_function_or_method' object is not subscriptable

In [ ]:
#Creating a scatter plot that shows the number of mice still alive through the course of treatment (Survival Rate)